export const allProducts = [
	{
		id: 1,
		name: "Flickrrr",
		slug: "flickrrr",
		tagline: "Anonymous feedback app built with Next.js",
		description:
			"Flickr is an anonymous feedback app built with Next.js. Users can manage incoming messages through a dashboard, accepting or declining feedback. Share your profile link to receive anonymous messages. The app uses Tailwind CSS, Radix UI, NextAuth, and OpenAI for a secure and seamless experience.",
		websiteUrl: "https://flickrrr.vercel.app",
		tags: ["Next.js", "Tailwind CSS", "TypeScript", "NextAuth"],
		createdAt: new Date("2024-08-17"),
		approvedAt: new Date("2024-08-20"),
		status: "approved" as const,
		submittedBy: "yalok6321@gmail.com",
		voteCount: 560,
	},
	{
		id: 2,
		name: "ShrinkIt",
		slug: "shrinkit",
		tagline: "URL shortener with advanced features and user authentication",
		description:
			"Developed a modern URL shortening application with advanced features including password protection, QR code generation, and link management. Implemented user authentication using built-in middleware and cookies. Utilized MongoDB with Mongoose for efficient data handling.",
		websiteUrl: "https://shuck.vercel.app",
		tags: ["URL Shortener", "Authentication", "MongoDB"],
		createdAt: new Date("2024-09-16"),
		approvedAt: new Date("2024-09-21"),
		status: "approved" as const,
		submittedBy: "yalok6321@gmail.com",
		voteCount: 430,
	},
	{
		id: 3,
		name: "Guidly",
		slug: "guidly",
		tagline: "Web app for connecting mentors and mentees",
		description:
			"A web app to connect mentors and mentees based on skills and interests. Features include profile creation, matchmaking, connection management, and notifications.",
		websiteUrl: "https://guidly.vercel.app",
		tags: ["Web App", "Mentorship", "Networking"],
		createdAt: new Date("2024-12-12"),
		approvedAt: new Date("2024-12-15"),
		status: "approved" as const,
		submittedBy: "yalok6321@gmail.com",
		voteCount: 598,
	},
	{
		id: 4,
		name: "Arise",
		slug: "arise",
		tagline: "A React-based e-commerce platform",
		description:
			"A React-based e-commerce platform that offers an immersive shopping experience. The app uses Firebase for the backend, handling user authentication, data storage, and real-time updates. Stripe is integrated for secure payment processing, with Firebase Cloud Functions generating clientSecrets.",
		websiteUrl: "https://a-rise-sigma.vercel.app",
		tags: ["React", "Firebase", "Stripe", "E-commerce"],
		createdAt: new Date("2024-08-01"),
		approvedAt: new Date("2024-08-03"),
		status: "approved" as const,
		submittedBy: "yalok6321@gmail.com",
		voteCount: 541,
	},
	{
		id: 5,
		name: "Sumera",
		slug: "sumera",
		tagline: "A comprehensive finance management application",
		description:
			"A comprehensive finance management application designed to help users gain control over their finances. This project is designed to help you manage your finances effectively by tracking your expenses, setting budgets, and analyzing your spending habits.",
		websiteUrl: "https://sumera.vercel.app",
		tags: ["Finance", "Budget", "Analytics"],
		createdAt: new Date("2024-09-27"),
		approvedAt: new Date("2024-09-29"),
		status: "approved" as const,
		submittedBy: "yalok6321@gmail.com",
		voteCount: 361,
	},
	{
		id: 6,
		name: "E-manage",
		slug: "e-manage",
		tagline: "A full stack event management application",
		description:
			"A full stack event management application built, frontend with react, backned using express, mongodb, and integrated real time event attendences and event creation using socket.io",
		websiteUrl: "https://emanage.vercel.app",
		tags: ["Event Management", "Real-time", "Full Stack"],
		createdAt: new Date("2025-02-10"),
		approvedAt: new Date("2025-02-12"),
		status: "approved" as const,
		submittedBy: "yalok6321@gmail.com",
		voteCount: 283,
	},
	{
		id: 7,
		name: "Quizzo",
		slug: "quizzo",
		tagline: "A Quiz Management System",
		description:
			"A Quiz Management System where teachers can log in, create, edit, and delete quizzes, frontend built using React, and backend with Express, and Prisma.",
		websiteUrl: "https://quizzo-liart.vercel.app",
		tags: ["Quiz", "Frontend", "Backend", "Prisma"],
		createdAt: new Date("2025-02-14"),
		approvedAt: new Date("2025-02-16"),
		status: "approved" as const,
		submittedBy: "yalok6321@gmail.com",
		voteCount: 73,
	},
	{
		id: 8,
		name: "RBAC",
		slug: "rbac",
		tagline: "Role-Based Access Control",
		description:
			"A Role-Based Access Control system featuring user management, dynamic roles and permissions, and a clean UI. Easily manage users and control access with flexible role editing and JSON profile views.",
		websiteUrl: "https://rbac-alok.vercel.app",
		tags: ["Role-Based", "Access Control", "User Management"],
		createdAt: new Date("2024-11-22"),
		approvedAt: new Date("2024-11-24"),
		status: "approved" as const,
		submittedBy: "yalok6321@gmail.com",
		voteCount: 109,
	},
	{
		id: 9,
		name: "Recipe Wiz",
		slug: "recipe-wiz",
		tagline: "A dynamic and responsive recipe discovery app",
		description:
			"A dynamic and responsive recipe discovery app allowing users to search, filter, and explore a wide variety of recipes based on cuisine, meal type, time, and difficulty.",
		websiteUrl: "https://recipewiz.vercel.app",
		tags: ["Recipe", "Search", "Filter", "Responsive", "Dynamic"],
		createdAt: new Date("2024-11-07"),
		approvedAt: new Date("2024-11-09"),
		status: "pending" as const,
		submittedBy: "yalok6321@gmail.com",
		voteCount: 123,
	},
	{
		id: 10,
		name: "Money Map",
		slug: "money-map",
		tagline: "A simple web application for tracking personal finances",
		description:
			"A simple web application for tracking personal finances, visualizing transactions, and managing budgets. Here, you can first specify your budgets and then add transactions to them. The app provides a clear overview of your spending habits and helps you manage your finances effectively.",
		websiteUrl: "https://moneymap-alok.vercel.app",
		tags: ["Finance", "Budget", "Analytics"],
		createdAt: new Date("2025-02-17"),
		approvedAt: new Date("2025-02-19"),
		status: "pending" as const,
		submittedBy: "yalok6321@gmail.com",
		voteCount: 85,
	},
	{
		id: 11,
		name: "EmageXpert",
		slug: "emageXpert",
		tagline: "EmageXpert is an intuitive image editor",
		description:
			"EmageXpert is an intuitive image editor that allows users to apply filters, add text overlays with customizable colors and backgrounds, and draw shapes like rectangles, circles, and lines. Built with modern web technologies.",
		websiteUrl: "https://emagexpert.vercel.app",
		tags: ["Image Editor", "Filter", "Text Overlay", "Shape Drawing"],
		createdAt: new Date("2024-10-19"),
		approvedAt: new Date("2024-11-09"),
		status: "pending" as const,
		submittedBy: "yalok6321@gmail.com",
		voteCount: 63,
	},
	{
		id: 12,
		name: "Harmony Hub",
		slug: "harmony-hub",
		tagline: "Harmony Hub is a cutting-edge music academy app",
		description:
			"Harmony Hub is a cutting-edge music academy app built with Next.js. It transforms music education by providing an intuitive platform for students, teachers, and administrators. With features for interactive lessons, performance tracking, and streamlined administration, Harmony Hub enhances the learning experience and simplifies school management.",
		websiteUrl: "https://recipewiz.vercel.app",
		tags: [
			"Music",
			"Academy",
			"Interactive Lessons",
			"Performance Tracking",
		],
		createdAt: new Date("2024-05-31"),
		approvedAt: new Date("2024-07-09"),
		status: "pending" as const,
		submittedBy: "yalok6321@gmail.com",
		voteCount: 32,
	},
	{
		id: 13,
		name: "Lock Crafter",
		slug: "lock-crafter",
		tagline: "Unlock the power of React Password Generator",
		description:
			"Introducing a sleek React Password Generator leveraging useRef, useEffect, and useCallback hooks. It automatically generates strong passwords, updates in real-time, and offers a quick copy feature for seamless integration.",
		websiteUrl: "https://lockcrafter.vercel.app",
		tags: ["Password Generator", "React", "Hooks", "Quick Copy"],
		createdAt: new Date("2024-05-08"),
		approvedAt: new Date("2024-07-09"),
		status: "pending" as const,
		submittedBy: "yalok6321@gmail.com",
		voteCount: 54,
	},
];
